---
output:
  pdf_document: default
  html_document: default
---

# Appendix

> Jadon Fowler, STA 570 Section 1
>
> 2023/03/09

```{r, message=FALSE, warning=FALSE, results='hide'}
library(ggplot2)
library(dplyr)
library(mosaic)
library(Lock5Data)
```

1)
```{r}
ME <- qt(.95, 40-1) * (1.3 / sqrt(40))
c(11.2-ME, 11.2+ME)
```

2)
```{r}
ME <- qt(.975, 100-1) * (1.1 / sqrt(100))
c(1.1-ME, 1.1+ME)
```

3)
```{r}
(qnorm(.995) * (4/1)) ^ 2
```

4)
```{r}
# Bootstrap method
data("FloridaLakes", package = "Lock5Data")
BootDist <- mosaic::do(1000) * 
  mosaic::resample(FloridaLakes) %>% 
  summarise(Bootxbar=mean(AvgMercury))
quantile(BootDist$Bootxbar, probs=c(0.025, 0.975))

# Asymptotic method
mercury <- FloridaLakes$AvgMercury
ME <- qt(.975,length(mercury)-1) * (sd(mercury) / sqrt(length(mercury)))
c(mean(mercury)-ME, mean(mercury)+ME)
```

5)
```{r}
# Bootstrap method
data("Cereal", package = "Lock5Data")
BootDist <- mosaic::do(1000) * 
  mosaic::resample(Cereal) %>% 
  summarise(Bootxbar=mean(Sugars))
quantile(BootDist$Bootxbar, probs=c(0.05, 0.95))

# Asymptotic method
sugar <- Cereal$Sugars
ME <- qt(.95,length(sugar)-1) * (sd(sugar) / sqrt(length(sugar)))
c(mean(sugar)-ME, mean(sugar)+ME)
```
